In [1]:
!pip3 install numpy

In [2]:
import numpy as np

In [3]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。

In [17]:
a=np.arange(0,21,1)

In [18]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [25]:
#呈上題，將以上數列取出偶數。

In [26]:
b=np.arange(0,21,2)

In [27]:
print(b)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [30]:
#呈1題，將數列取出3的倍數。

In [31]:
c=np.arange(0,21,3)

In [32]:
print(c)

[ 0  3  6  9 12 15 18]
